/* package codechef; // don't place package name! */

import java.util.*;
import java.io.*;


/* Name of the class has to be "Main" only if the class is public. */
class Codechef
{
    public static void prc(int k)
    {
        if(k==1)
        {
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println(".XXX....");
            System.out.println(".XOX....");
            System.out.println(".XXX....");
            System.out.println("........");
            System.out.println("........");

        }
        if(k==2)
        {
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("XXX.....");
            System.out.println("O.X.....");

        }
        if(k==3)
        {
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("XXXX....");
            System.out.println("O..X....");

        }
        if(k==4)
        {
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("XXXXX...");
            System.out.println("O...X...");

        }
        if(k==5)
        {
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("XXX.....");
            System.out.println("..XX....");
            System.out.println("O..X....");

        }
        if(k==6)
        {
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("XXXX....");
            System.out.println("...X....");
            System.out.println("O..X....");

        }
        if(k==7)
        {
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("XX......");
            System.out.println(".XXX....");
            System.out.println("...X....");
            System.out.println("O..X....");

        }
        if(k==8)
        {
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("XXX.....");
            System.out.println("..XX....");
            System.out.println("...X....");
            System.out.println("O..X....");

        }   
        if(k==9)
        {
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("XX......");
            System.out.println(".XX.....");
            System.out.println("..XX....");
            System.out.println("...X....");
            System.out.println("O..X....");

        }
        if(k==10)
        {
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("XXX.....");
            System.out.println("..X.....");
            System.out.println("..XX....");
            System.out.println("...X....");
            System.out.println("O..X....");
        } 
        if(k==11)
        {
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("XXX.....");
            System.out.println("..XX....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("O..X....");
        } 
        if(k==12)
        {
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("XXXX....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("O..X....");
        } 
        if(k==13)
        {
            System.out.println("........");
            System.out.println("........");
            System.out.println("XX......");
            System.out.println(".XXX....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("O..X....");
        } 
        if(k==14)
        {
            System.out.println("........");
            System.out.println("........");
            System.out.println("XXX.....");
            System.out.println("..XX....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("O..X....");
        } 
        if(k==15)
        {
            System.out.println("........");
            System.out.println("........");
            System.out.println("XXXX....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("O..X....");
        } 
        if(k==16)
        {
            System.out.println("........");
            System.out.println("XX......");
            System.out.println(".XXX....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("O..X....");
        } 
        if(k==17)
        {
            System.out.println("........");
            System.out.println("XXX.....");
            System.out.println("..XX....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("O..X....");
        } 
        if(k==18)
        {
            System.out.println("........");
            System.out.println("XXXX....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("O..X....");
        } 
        if(k==19)
        {
            System.out.println("XX......");
            System.out.println(".XXX....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("O..X....");
        } 
        if(k==20)
        {
            System.out.println("XXX.....");
            System.out.println("..XX....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("O..X....");
        } 
        if(k==21)
        {
            System.out.println("XXXX....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("O..X....");
        } 
        if(k==22)
        {
            System.out.println(".XXX....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("O..X....");
        } 
        if(k==23)
        {
            System.out.println("..XX....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("O..X....");
        } 
        if(k==24)
        {
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("O..X....");
        } 
        if(k==25)
        {
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...XX...");
            System.out.println("O...X...");
        } 
        if(k==26)
        {
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...XX...");
            System.out.println("....X...");
            System.out.println("O...X...");
        } 
        if(k==27)
        {
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...XX...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("O...X...");
        } 
        if(k==28)
        {
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...XX...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("O...X...");
        } 
        if(k==29)
        {
            System.out.println("...X....");
            System.out.println("...X....");
            System.out.println("...XX...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("O...X...");
        } 
        if(k==30)
        {
            System.out.println("...X....");
            System.out.println("...XX...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("O...X...");
        } 
        if(k==31)
        {
            System.out.println("...XX...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("O...X...");
        } 
        if(k==32)
        {
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("O...X...");
        } 
        if(k==33)
        {
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....XX..");
            System.out.println("O....X..");
        } 
        if(k==34)
        {
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....XX..");
            System.out.println(".....X..");
            System.out.println("O....X..");
        } 
        if(k==35)
        {
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....XX..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println("O....X..");
        } 
        if(k==36)
        {
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....XX..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println("O....X..");
        } 
        if(k==37)
        {
            System.out.println("....X...");
            System.out.println("....X...");
            System.out.println("....XX..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println("O....X..");
        } 
        if(k==38)
        {
            System.out.println("....X...");
            System.out.println("....XX..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println("O....X..");
        } 
        if(k==39)
        {
            System.out.println("....XX..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println("O....X..");
        } 
        if(k==40)
        {
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println("O....X..");
        } 
        if(k==41)
        {
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....XX.");
            System.out.println("O.....X.");
        } 
        if(k==42)
        {
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....XX.");
            System.out.println("......X.");
            System.out.println("O.....X.");
        } 
        if(k==43)
        {
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....XX.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("O.....X.");
        } 
        if(k==44)
        {
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....XX.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("O.....X.");
        } 
        if(k==45)
        {
            System.out.println(".....X..");
            System.out.println(".....X..");
            System.out.println(".....XX.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("O.....X.");
        } 
        if(k==46)
        {
            System.out.println(".....X..");
            System.out.println(".....XX.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("O.....X.");
        } 
        if(k==47)
        {
            System.out.println(".....XX.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("O.....X.");
        } 
        if(k==48)
        {
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("O.....X.");
        } 
        if(k==49)
        {
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......XX");
            System.out.println("O......X");
        } 
        if(k==50)
        {
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......XX");
            System.out.println(".......X");
            System.out.println("O......X");
        } 
        if(k==51)
        {
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......XX");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println("O......X");
        } 
        if(k==52)
        {
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......XX");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println("O......X");
        } 
        if(k==53)
        {
            System.out.println("......X.");
            System.out.println("......X.");
            System.out.println("......XX");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println("O......X");
        } 
        if(k==54)
        {
            System.out.println("......X.");
            System.out.println("......XX");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println("O......X");
        } 
        if(k==55)
        {
            System.out.println("......XX");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println("O......X");
        } 
        if(k==56)
        {
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println("O......X");
        } 
        if(k==57)
        {
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println("O.......");
        } 
        if(k==58)
        {
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println("........");
            System.out.println("O.......");
        } 
        if(k==59)
        {
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println("........");
            System.out.println("........");
            System.out.println("O.......");
        } 
        if(k==60)
        {
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("O.......");
        } 
        if(k==61)
        {
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("O.......");
        } 
        if(k==62)
        {
            System.out.println(".......X");
            System.out.println(".......X");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("O.......");
        } 
        if(k==63)
        {
            System.out.println(".......X");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("O.......");
        } 
        if(k==64)
        {
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("........");
            System.out.println("O.......");
        }  
        
    }
	public static void main (String[] args) throws java.lang.Exception
	{
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in)); 
        BufferedWriter bw=new BufferedWriter(new OutputStreamWriter(System.out));
        int t=Integer.parseInt(br.readLine());
        int[] kList=new int[t];
        //String[] sList =  new String[t];
        for(int i=0;i<t;i++)
        {
            
            int k=Integer.parseInt(br.readLine());
            kList[i]=k;

        }
        for(int i=0;i<t;i++) 
            { 
                prc(kList[i]);
                //bw.write(String.valueOf(h));
                //bw.newLine();
            }
        br.close();
        bw.close();  
	}
}
